### ISSUE TITLE
SMT4A element_recipes.js should say Ometeotl instead of Omoteotl

### ISSUE THREAD

**Issue by hyunlee11037** [aqiu384/aqiu384.github.io#3]
Hello aqiu382, I have forked your project over since I was using your SMT4A page for web scraping (hobby purposes). I noticed there was a typo in Ometeotl's name in elements_recipes.js, where it says Omoteotl, and this is preventing fusion tables from rendering for demons such as Mahamayuri.

When I made the changes on the forked project, the issue seems to be instantly fixed.

Thank you!

**Comment by aqiu384** [comment]
Fixed as of 818a71b19fbd3ce5912ec70892141aee7dd03cb5
